apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doriscluster-sample
    app.kubernetes.io/part-of: doris-operator
  name: doriscluster-sample
spec:
  adminUser:
    name: root
    password: ${password}
  feSpec:
    replicas: 1
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi
    image: apache/doris:fe-2.1.8
    configMapInfo:
      configMapName: fe-conf
      resolveKey: fe.conf
    persistentVolumes:
    - mountPath: /opt/apache-doris/fe/doris-meta
      name: meta
      persistentVolumeClaimSpec:
        # when use specific storageclass, the storageClassName should reConfig, example as annotation.
        storageClassName: doris-fe-storage
        accessModes:
          - ReadWriteOnce
        resources:
          # notice: if the storage size less 5G, fe will not start normal.
          requests:
            storage: 20G
    service:
      type: NodePort
      servicePorts:
      - nodePort: 31001
        targetPort: 8030
      - nodePort: 31002
        targetPort: 9030
  beSpec:
    replicas: 1
    limits:
      cpu: 3
      memory: 6Gi
    requests:
      cpu: 2
      memory: 4Gi
    image: apache/doris:be-2.1.8
    configMapInfo:
      configMapName: be-conf
      resolveKey: be.conf
    persistentVolumes:
    - mountPath: /opt/apache-doris/be/storage
      name: be-storage
      persistentVolumeClaimSpec:
        storageClassName: doris-be-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 80G
    service:
      type: NodePort
      servicePorts:
      - nodePort: 31006
        targetPort: 8040
