@startuml
!include <archimate/Archimate>
!include <logos/kafka>
!include <cloudinsight/hdfs>
!include <cloudinsight/mysql>
!include <cloudinsight/file>
!include <cloudogu/tools/k8s>
!include <awslib/AWSCommon>
!include <office/Concepts/application_web>
!include <tupadr3/font-awesome-6/warehouse>
!include ../lib/debezium.puml
!include ../lib/flink.puml
!include ../lib/hive.puml
!include ../lib/spark.puml
!include ../lib/doris.puml
!include ../lib/dataX.puml

!theme cerulean-outline

title Data Engine's Dataflow Architecture

frame "结构化数据" as structData {
  left to right direction

  database "<$mysql>\nmysql" as mysql
  database "<$doris>\ndoris" as doris
  rectangle "<$application_web>" as application

  frame "数据链路" as dataflow {

    rectangle "全量" as full {
      rectangle "<$dataX>" as datax

      mysql --> datax: 全量采集
      datax --> doris: 全量数据写入doris并加工
    }
    rectangle "增量" as cdc {
      left to right direction

      rectangle "<$debezium>" as debezium
      queue "<$kafka>" as kafka
      rectangle "<$flink>\nflink" as flink

      mysql --> debezium: 增量采集
      debezium --> kafka: 推送增量数据
      kafka --> flink: 消费增量数据
      flink --> doris: 增量数据写入doris并加工
    }
  }
  doris --> application: 数据查询
}

frame "非结构化数据" as unstructData {
  left to right direction

  rectangle "数据来源" as datasource {
      folder "<$file>" as file
      cloud "website" as website
  }
  rectangle "数据仓库" as datawarehouse {
    rectangle "<$spark>\nSpark" as sparkRect
    database "<$hive>\nHive" as hiveRect
    folder "<$hdfs>\nHdfs"  as hdfs
  }
  rectangle "数据集市" as datamarket {
    database "<$doris>\n结构化数据存储" as structStorage 
    database "半结构化数据存储" as semiStructStorage{
      component "mongoDB"
      component "redis"
      component "elasticsearch"
    }
    folder "非结构化数据存储"  as unstructStorage {
      component "minio"
      component "s3"
      component "obs"
      component "oss"
    }
  }
}

@enduml

