sprite $dataX [325x101/16] {
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEDEEEEEEEEEEEEDDDDDDEDDDDEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCDDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCDCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDEEEEEEEEDEEEDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCBBCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDEEEEEEEEEEEDDDCCDDDDDDCCDDEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCBBCCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDEEEDEDEEEDDDDCCDCCCCCCCDDEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCBBCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEDDDCCCCCCCCCCCDDDEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBBCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEDEEEEDDDCCCCCCCCCCBCDDDEEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBBBCCCBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDEDDDDDCCCCCCCCBBBCDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBBBBCBBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEDDDDCCBCBBBBBBBCDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDCCDDDDDDDDDDDDDDDDDDDDDDCCBBBBBBBBBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEDDDDCCCBBBBBBBBBCDDDEEEEEEEEEEEEEEDDDDDDDDDEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDCCBBABBBBBBBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDDCCCBBBBBBBBBCCDDDEEEEEEEEEEEEDDDDDDDDDDDDDEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCDDDDDDDDDDDDCCCCCCCCCCCCCDDDDDDDDDDDDDDCCBBAABBBBBBCCCDDDDDDDDDDDDDDDDDDDDDDDDDEDDDDCCBBBBBBBBBBCDDDEEEEEEEEEEEEEDDDDDDDDDDDDDEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDCCCCCCCCCCCCCDDDDDDDDDDDDDCCCBBAAAABBBBBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBBBAAAAABBCDDEEEEEEEEEEEEEEDDDDDDDDDDDDDEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDCCCCCCCCCCCCCCDDDDDDDDDDDDDDCCBBAAAAABBBBCCCDDDDDDDDDDDDDDDDDEDDDDDDCCBBAAAAAAABBCDDDEEEEEEEEEEEEEDDDDDDDDDDDDDEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDCCCCCCCCCCCCCCDDDDDDDDDDDDDDCCBBAAAAAAABBCCCDDDDDDDDDDDDDDDDEDDDDCCBBAAAAAAAABBCDDDEEEEEEEEEEEEEDCCCCCCCCCCDDDEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBBCCCCCCCCCCCCCCCCCBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDCCCBCCCCBBBCCCDDDDDDDDDDDDDDCCBBAAAAAAAABBCCDDDDDDDDDDDDDDDDDDCCCBBAAAAAAAABCCDDEEEEEEEEEEEEEEDCCCCCCCCCCCDDEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDCCBBBCCBBBBBCCDDDDDDDDDDDDDDCCBBAAAAAAAABBCCCDDDDDDDDDDDDDDDCCCBBAA999AAABCCDDDEEEEEEEEEEEEEDCCCCCCCCCCCCDEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDCCBBBBBBBBBBBCCDDDDDDDDDDDDDCCCBBAAA99AAAABCCCCDDDDDDDDDDDCCCBBAA9999AABBBCDDEEEEEEEEEEEEEEDCCCCCCCCCCCCDDEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCBBBBBCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCBBBBBBBBBBBCDDDDDDDDDDDDDDDCCBBAAA9999AABBCCCDDDDDDDDDCCBBAA99999AAABCCDDDEEEEEEEEEEEEEDCCCCCCCCCCCCDDEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBBCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDCBBBBBBBBBBBBCCDDDDDDDDDDDDDCCCBBAAA9999AAABCCCDDDDDDCCCBBAA99999AAABBCDDDEEDEEEEEEEEEEDCCBBBCCCCCBCCDEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCBCCCCBBBBBCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDCCBBBBBBBBBBBBCCDDDDDDDDDDDDDDCCBBAAA99999AABBCCCDDDCCCBBAA99999AAABBCDDDEEEEEEEEEEEEEDCCBBBBBCCBBBCDEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCBCCCCBBBBBCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDCCBBABBBBBABBBCDDDDDDDDDDDDDDDCCBBAA999999AABBCCCCCCBBAA9988999AABBCCDDEEEEEEEEEEEEEDDCBBBBBBBBBBCDDEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCBCCCCBBBBBCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDCCBAAABBAAAABBCDDDDDDDDDDDDDDDCCBBAAA999899AABBBBBBAAA9988999AABBCDDDDEEEEEEEEEEEEDDCBBBBBBBBBBCCDEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBCCCCCCCCCCCCCCBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCBBAAABAAAAABBCDDDDDDDDDDDDDDDCCBBAA9998899999999999988899AAABBCDDDEEEEEEEEEEEEEDDCBBBBBBBBBBBCDEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBCCCCCCCCCCCCCCBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDCBBAAAAAAAAABBCDDDDDDDDDDDDDDDCCBBAAA99888888888888888999AABBCDDDEEEEEEEEEEEEEDCCBBABBBBBABBCDDEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBBCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAAAAAAAAAABCCDDDDDDDDDDDDDDDCCBBAAA99888888888888899AAABBCDDDDEEEDEEEEEEEEDDCBBAAABAAAABCDDEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCBBBBCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAAAAAAAAAABCCDDDDDDDDDDDDDDDCCCBAAA998888888888899AAABBCCDDEEEEEDEEEEEEDDDCBAAAAAAAAABBCDEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCBBBBCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBAAAAAAA9AABBCCDDDDDDDDDDDDDDCCBBAA99988888888899AAABBCDDDDEEEEEEEEEDEEDDCBBAAAAAAAAABCDDEEEEEEEEEEEEEEEED
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCBBCCBCBCBBCBBBCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCBCCCCBBBBCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDCDCCDCDDDDDDDDDDDDDDDDDDDCCBAAA99AA99AABBCDDDDDDDDDDDDDDDDCCBBAA99888888899AAABBCCDDEEDDEEEEEEEEEDCCBAAAAAAAAABBCDDEEEEEEEEEEEEEDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCBBCBCBCBBBCBBBCBBCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCBCCCCBBBBCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCDDCDCDDDDDDDDDDDDDDDDDDCBBAA9999999AABBCDDDDDDDDDDDDDDDDCBBAA9998888899AAABBCCDDDEEDDEEEEEEEEDDCBBA9A9AAAAABBCDDEEEEEEEEEDDEDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCBCBCBCBCCBBCCBBBCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCBBBBBCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDCDDCDDDDDDDDDDDDDDDDDDCCBBAA9999999AABBCDDDDDDDDDDDDDDDDCCBBAA99888999AABBCCDDDEEDEEEEEDEEDDDCBAA999999AABBCDDEEEEEDDDDDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCBBCCBCBBCBCBBCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCBBBBCCCCCCCCCCCBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCDDDCCDDDDDDDDDDDDDDDDDDDCCBAA99999999AABBCDDDDDDDDDDDDDDDCCCBAAA999999AABBCCDDDEEEDDDDDEEEEDDCBAA9999999AABCCDDEEDDDDDDDDDDDDDDDDD
CCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCBCBBCCCBCBCBCBBBCBBBCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCBBCCCBBBBCCCCCCCCCCCBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCDCDCDDDDDDDDDDDDDDDDDDDDDDCCBAA99999999AABBCDDDDDDDDDDDDDDDDCCBBAAAAAAAABBCCDDDDDDDDEEDEEEEDDCBBA9999999AABBCDDEEDDDDDDDDDDDDDDDDDD
CCCCCCCCC976666766666666666666666679BCBBCCBBCBBBCBBCBBB522233223222222222222222222222222222222223326BB82222222222222222222233333332222333333333332ABB33333333333333333333333333333333333333333333BDDCDDCDDDDDDDDDDDDDDDDDDDDDCBBAA99899899AABCCDDDDDDDDDDDDDDDDCBBBABBBAABBCCDDDDDDDDEEEEEEDDDCBBA99999999ABBCDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCB0000000000000000000000000000248CCBBCBBBBCBBBB600000000000000000000000000000000000000000008BBB0000000000000000000000000000000000000000000BCC10000000000000000000000000000000000000000001DCDDCDDDDDDDDDDDDDDDDDDDDDDDCCBBA998888899AABCCDDDDDDDDDDDDDDDDCCBBBBBBBBCCDDDDDDDDEEDDDEDDDCBAA99999899ABBCDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCC20000000000000000000000000000014CBBBBBBCBCBBB1000000000000000000000000000000000000000003CBBB6000000000000000000000000000000000000000009CCC9000000000000000000000000000000000000000000BDDDDCDCDDDDDDDDDDDDDDDDDDDDDDCCBAA998888889AABCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEDEEEEEDDDDDDCBAA99888899AABBCDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC100000000000000000000000000000005CBBBBBBBBBCA00000000000000000000000000000000000000001CCCCBB10000000000000000000000000000000000000003CCCCC400000000000000000000000000000000000000005DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBAA9988888899ABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDCCBBA988888899ABBCDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC5000024344444444444444210000000001ABBCBBBBBBC60058888884000088888888888100027888788309DDCCBBA000344444788878881000088888787444443000CDDDCCC1006888888100048888888888700007888888711EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBAA988888889AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDEDDDCCBBA988888889AABCCDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC700008EEDDDEDDDDDDDDDDDED95200000008BBBBBBBBCC36DDDDDDD20006DDDDDDDDDDD60001DDEDDDDDADDDCCBBB409DDDDDDDDDDDDDD10001EDDDDDDDEDDEDDA07DDDDCCCB2CEEDEEDC0000CEEEEEEEEEED10006EEEEDEEEBEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA9988888889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBA988888889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC700008DDDDDEDDDDDDDDDDDDDDDDC60000009BBBBBBBBCCDDDDDDDD0000CDDDDDDDDDDDB00009DDDDDDDDCDDCBBBBCCDDDDDDCDDDDDDDD10001DEDDDDDDDDDDDEDDDDDCCCCCCDDEEEDED60002DEEDDDDDDDDE60001EEEEEEDEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA9988888889AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBAA9988888899AABCDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDDDCDDDDDDDDDCDDDDDDDDDC200000ACBCBBBBBCCCDDCCC60003DDDCCCCCCCCCC20003DDCCCCCCDCCCBBBBBCCCDCCCCDCCCCCCC10001DDDDCCCDDDDDDDDDDDCCCCCCCDDDDCDDD1000AEEDDDDDDDDDDC0000BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBA99888778899AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA9988778889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC700008DDCCCCCCCCCCCCCCCCCCCDDCDD200002CBBBBBBBBCCCCCCC10008DDCCCCBBCCCCB70000CCCCCCBBBCCBBBBBBBCCCCBBCBBBBCBBB10001EDCCCCCCCCDDCDCCCCCCCCCCCCDDDDDCB0000EDEDDDDCCDDDDD20003DDDDDCDDDDDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA99887777889AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA9987777889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC700008DDCCCCCCCCCCCCCCBBCCCCCCCDD20000ACBBBBBBBCBBBBBA0000DDDCCBBBBBBBBCC00006CBBBBBBBBBBBBBBBBBBBABBBBBBBBBBB00001DDCCCBBCCCCCCCCCCCCCCCCCCCCCCCCC30005EDDDCCCCCCCCCC60000DDCDCDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA99877777889AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA98877777899AABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCBCCCCCCCCCCCBBBCBCCCCCCB00002CCCBBBBBBBBBBB40003DDCCBBBBBBBBBBB20002CCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCCCBBCCCCCCCCCBBCCCCCCCCCCCCC0000BDEDCCCCCCCCCCDC00007DDCCCCDCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBAA98877777899AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA98877777889AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCCBBBBBBBBBBCCC30000ACCBBBBBBBBBBB1000ADDCCBBBBBBBBBBB90000BCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCCBBBCCCCCCCCBBBCCCCCCCCCCCC90001EEDDDCCCCCCCCCCC20002DDDCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBA998877677889AABBCDDDDDDDDDDDDDDDDDDDDDDDDCCBAA98877677889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBBCCC900003CBBBBBBBBBBB90000DDDCBBBBBBBBBBBBB00004CBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCCBBBCCCCCCCCBBBCCCCCCCCCCCC30006EEDDCCCCCCCCCCCC90000CDDCDCCDCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA998776677899AABCCDDDDDDDDDDDDDDDDDDDDDDCBBAA98877677889AABBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBCBBBBC00001CCBBBBBBBBBB30005DCCCBBBBBBBBBBBBB40000CCBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCCBBBCCCCCCCCBBBCCCCCCCCCCCC0000CEDDCCCCCCCCCCCCDC00005DDCCCDDCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA998776677899AABCCDDDDDDDDDDDDDDDDDDDDCBBAA988776677899AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBCBBBB10000DCBBBBBBBBBB0000ADDCBBBBBBBBBBBBBBA00008CBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCCBBBCCCCCCCCBBBCCCCCCCCCCC70002DEDCCCCCCCCCCCCCCC40001DDDDCDCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA9988766677889AABCCDDDDDDDDDDDDDDDDDDCBBA9988766667889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBBCBBC20000DCCBBBBBBBB90002DDDCBBBBBBBBBABBBBC10002CCBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCCBBBCCCCCCCCBBCCCCCCCCCCCC20006DEDDCCCCCCCCCCCCDCA00009DDCCCDCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBAA9987766667889AABBCCDDDDDDDDDDDDDDDDCCBBA99887665678899AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBCBCBBBB30000DDCBBBBBBBB20006DDCCBBBBBBBBBBBBBBB50000BCBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCBBBBCCCCCCCCBBCCCCCCCCCCCC0000CEDDCCCCCCCCCCCCCCCC00003DDCDDCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBAA9987766667889AABBCCDDDDDDDDDDDDDDDDDDCCBBA99887666678899AABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBCBCBB20000DCCCBBBBBBB0000CDDCCBBBBBBBBBBBBBBBA00005CBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCBBBBCCCCCCCBBBCCCCCCCCCCC50002DEDDDCCCCCCCCCCCCCCC50000EDCCCDCCCCCCCCCCCCCCDDCCCCDDDDDDDDDDDDDDDDCCBAA9988766667889AABBCCDDDDDDDDDDDDDDDDDDDDCCBBA9988766667889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBBCBBB10000DDCBBBBBBB6000011100000000000000000000001DBBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DDCCBBBCCCCCCCCBBBCCCCCCCCCCC1000021100000000000000100100006DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDCBBAA9887766678899ABBCCCDDDDDDDDDDDDDDDDDDDDDCCBBAA988766677899AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBBBBBB00001DDCBBBBBBB1000000000000000000000000000000ACBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DCCCBBBCCCCCCCCBBBCCCCCCCCCCB0000000000000000000000000000001ECCCCCCCCCCCCCCCCCCCCCCCCDDDDDCCDDDDDDDDCBBAA988776667889AABBCCCDDDDDDDDDDDDDDDDDDDDDDDCCBBAA988776678899AABCDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBCBBBBA00002DCCCBBBBBB00000000000000000000000000000003CBBBBBBBBBBBBBBBBBBBBBBBBBBB00001DCCCBBBCCCCCCCCBBCCCCCCCCCCC40000000000000000000000000000000ADDCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCDDDDDDCCBAA9988766778899ABBCCCDDDDDDDDDDDDDDDDDDDDDDDDDCCBBA998877677889AABBCDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBBBBB400006DDCBBBBBB400001111111111111111111111100000CCBBBBBBBBBBBBBBBBBBBBBBBBBB00001DCCCBBBCCCCCCCBBBCCCCCCCCCCC100011111111111111111111111000003DDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDCCBAA998877667889AABBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBAA98877677889AABCCDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBBCBB00000CDCBCBBCBB10005DDDDDDDDDDDDDDDDDDDDDDD400005CBBBBBBBBBBBBBBBBBBBBBBBBBB00001DCCCBBBCCCCCCCBBBCCCCCCCCCC90000CEEEEDDDDDDDDDEEEEEDDDDE00000DDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCBBA998877777889AABBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBAA99877777899ABBCCDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBBBC300002DDCCBBBBB80000CDDDDDDDDDDDDDDDDDDDDDDDA00001CBBBBBBBBBBBBBBBBBBBBBBBBBB00001DCCBBBBCCCCCCCBBBCCCCCCCCCC30002DEEEDDDDDDDDEEEEEEDEEEEE400006DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCBAA988777778899ABBCCCDDDDDCDDDDDDDDDDDDDDDDDDDDDDDDDCCBBAA99877778899ABBCDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBCBBB700000BDDCCBBBBB30002DDDDCCDCCCCCCCCCCCCCCCCCD100008CBBBBBBBBBBBBBBBBBBBBBBBBB00001DCCBBBBCCCCCCCBBBCCCCCCCCCC0000AEDDDDDDDDDDDDDDDDDDDDDDDA00000ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAA99887777889AABBBCCCDCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBAA9887777889AABCCDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBBC7000004DDDCBBBBBB00007DDCCCCCCCCCCCCCCCCCCCCCBC500002CCBBBBBBBBBBBBBBBBBBBBBBBB00001DCCBBBBCCCCCCCBBBCCCCCCCCC60000DEDDDCCCCCCDDDDDDDCDCDCDCD100008DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAA99887777889AABBCCCCCCCDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBAA9888778889AABCCDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBBBBBBBBBB3000001DDDCCBBBBB60000DDDCBBBBBBBBBBBBBBBBBBBBBBB00000ABBBBBABBBBBBBBBBBBBBBBBBB00001DCCBBBBCCCCCCCBBBCCCCCCCCC20002EDDDCCCCCCCCCCCCCCCCCCCCCC500002DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAA98887878899ABBCCCCCCCDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDCBBAA9888888899ABBCDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCBBBBCBBBCBBB40000000CDDDCCBBBBB00001DDDCBBBBBBBBBBBBBBBBBBBBBBB100003CBBBBBBBBBBBBBBBBBBBBBBBB00001DCCBBBBCCCCCCCBBCCBBCCCCC900006EDDCCCCCCCCCCCCCCCCCCCCCCCB00000ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAA99888888899ABBCCCCCCCDDDDDDDCCCCCCCCCCCCCCCDDDDDDDDDDDDDDCBBAA988888889AABCCDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC600008DDCCCCCCCCCCCCBCBC641000000009DDDCCBCBBB600003DDCBBBBBBBBBBBBBBBBBBBBBBBB400000BCBBBBBBBBBBBBBBBBBBBBBBB00001DCCBBBCCCCCCCCBBCBCCCCCCC100009DDCCCCCCCCCCCCCCCCCCCCCCCCC000002DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBAA9988888889AAABBCCCDCCDDDDDDCCCCCBBBBBBBBBCCCDDDDDDDDDDDDDDCCBBA9988888899AABCCDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCC1000011110000000000000000000000001CDDDDCCBBBBA000004DDCCBBBBBBBBBBBBBBBBBBBBBBB6000004CBBABBBBBBBBBBBBBBBBBBBB00001DCCBBBBCCCCCCBBBCCCBCBCC600000DDDCCCCCCCCCCCCCCCCCCCBCCCCC2000009CCCCCCCCCCCCCCCCCCCCCCCCCCCCCBAA99888888899ABBCCCCCDDCDDCDDCCCCCBBAAAAAAABBCCCDDDDDDDDDDDDDDCCBBAA988888899ABBCDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCB8000000000000000000000000000000006DDDDDCBBBBBB2000005DCCBBBBBBBBBBBBBBBBBBBBBBBB50000007CBBBBBBBBBBBBBBBBBBBBB600000ACCBBBCBCCCCCBBBCCBCCCBA000000CDCCCCCCCCCCCCCCCCCCCCCCCCBC0000000DCDCCCCCCCCCCCCCCCCCCCCCCCCCBBAA9888888899ABBCCCCCCDCCCCDDDCCCCBBAA99999AABBCCCCDDDDDDDDDDDDDDCBBAA99889899AABBCDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCC600000000000000000000000000000006CDEDDDCBBBBBB40000000BCCBBBBBBBBBBBBBBBBBBBBBBB8000000008BBBBBBBBBBBBBBBBBBBBB0000000BCBBBBBCCCCCBBBBCBBBBA00000003DCCCBCCCCCCCCCCCCCCCCCCCCC400000002CCCCCCBCCCCCCCCCCCCCCCCCCCBBAA998888899AAABBCCCCCCCCDCCDCCCCCBBAA9988899AABBCCCCDDDDDDDDDDDDDDCBBAA99999999AABCDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCC0000000000000000000000000000025BDDDDDDDCBCCBBB40000000008CBBBBBBBBBBBBBBBBBBBBBB500000000007BBBBBBBBBBBBABBBBB81000000008BBBBCCCCCBBBBBBBBBA0000000001BCBBBBBBBBBBBCCCCBCCCBCA300000000019CCCCCCCCCCCCCCCCCCCCCCCCBAA9988899999AABCCCCDDDCDDDDDCCCCCBBAA998888899AABBCCCCDDDDDDDDDDDDDDCCBAA99999999ABBCDDDDDDDDDDDDDDDDDDDD
CCCCCCCCC8777788888888888888888888ADDDDDDDDDDDCCCBBBCBB66678888889CCBBBBBBBBBBBBBBBBBBBBB666777888878CBBBBBBBBBBBBBBABB76667888888BBBCCBCCCBBBBBBBBBA6767788888BCCBBBBBBBBBBBBBBBCBCCBA666788988889CCCCCCCCCCCCCCCCCCCCCCCBBA999899999AABBCCCCCCCCCCCCCCCCCBBBAA99888888899AABBCCCCDDDDDDDDDDDDDDCCBAA9999999AABBCDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCCDDDDEEEDEEDEDDDDDDDDDDEDDDDDDDDDCCCCBBBBBBBBBCCCDDDDDDCBBBBBBBBBBBBBBBBBBBBBBBBBBCDDDDDDCCBBBBBBBBBBBBBBBBBBBBCCDDDDDDBBBBBBCCCBBBBBBBBBBBBCCDDDEDDCCCBBBBBBBBBBBBBBBBBBBCBCCCCDDDEDDDDCCCCCCCCCCCCCCCCCCCCCCBBAA999999999ABBCCCCCCCCCCCCCCCCCCBBAAA988888888899AABBCCCCDDDDDDDDDDDDDDCBBAA9999999ABBCDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCBBBBBBBBBBCCDDDDDDCCCBBBBBBBBBBBBBBBBBBBBBBBBCCDDDDDCCCBBBBBBBBBBBBBBBBBBBBCCCDDDCCCBBBBBBBBBBBBBBBBBBBCCCDDDDDDCCCBBBBBBBBBBBBBBBBBBBBBCCCDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCBAA99999999AABBCCCCCCCCCCCCCCCCCBBBAA998888888888899AABBCCCDDDDDDDDDDDDDDDCCBAA999A999ABBCDDDDDDDDDEDDDDDDDD
CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCBBBBBBBBBBCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCBBA99999999AAABCCCCCCCCCCCCCCCCCCBBAA99988888888888899AABBCCCDDDDDDDDDDDDDDDCCBAAAAAAAAAABCCDDEDDDDDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAA99999A9AAABBCCCCCCCCCCCDCCCCBBBAA99888888888888888999ABBCCCCDDDDDDDDDDDDDDCCBAAAAAAAAAABCDDDDDDDDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAA9999AAAAAABCCCCCCCCCCCCCCCCCBBBBA998888889888888888899AABBCCCDDDDDDDDDDDDDDDCCBBAAAAAAAABBCDDDDDDDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBAAA99AAAAAAABBCCCCCCCCCCCCCCCCBBBAA998888999AAAAAAA9999999AABBCCCDDDDDDDDDDDDDDDCCBAAAAAAAAABCCDDDDEDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAAAAAAAAAAABBCCCCCCCCCCCCCCCCCBBBA99888999AABBBBBBBAA9999999ABBCCCDDDDDDDDDDDDDDDCCBBBBBBBAABBCDDDDDDEDEEDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAAAAAAAAAABBCCCCCCCCCCCDCCCCCCBBAA9988899AAABBCCCCCCBAAA99999AABBCCCDDDDDDDDDDDDDDDDCBBBBBBBBBBBCDDDEEDDEEDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCBBBCCCCCCCCCCCCCCCCCCCCCCCCBBAAAAAAAABBBBBCCCCCCCCCCDDDCCCCBBBA9999999AABBCCDDDDCCCBBAA99999AABBCCCDDDDDDDDDDDDDDDCCBBBBBBBBBBCCDDDEDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBAAAAAAABBBBBCCCCCDCCDCCCDDCCCCBBAA999999AAABCCCDDDDDDDCCBBAA999999ABBCCCCDDDDDDDDDDDDDDDCBBCBBBBBBBCCDDDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBAAAAAABBBBBCCCCCCCCCCCDDDCCCCBBAA999999AABBCCCDDDDDDDDDCCBBBAA9999AABBCCCDDDDDDDDDDDDDDDDCCBCCBBBBBBCDDEDDDEDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBABBBBBBBBBCCCCCCCCCCCDDDCCCBBBAA999999AABBCCDDDDDDDDDDDDDCCBBAAA999AABBCCCDDDDDDDDDDDDDDDDCBCCCCCCCBCCDDEDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCCCDDDDCCCCCCBBAAA9999AAABBCCDDDDDDDDDDDDDDDCCCBAAAAAAAABBBCCDDDDDDDDDDDDDDDCCCCCCCCCCCCCDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCBBBCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBCCBBCCCCCCCCCCDDDCCCCCBBAAAA999AABBCCCDDDDDDDDDDDDDDDDDCCCBBAAAAAAABBBCCDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCBCCCCCBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBCCBBCCCCCCCCCCCDDDCCCCBBAAAAA9AAABBCCDDDDDDDDDDDDDDDDDDDDDCCBBAAAAAAABBCCCDDDDDDDDDDDDDDDCCCCDCCCCCCCDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCBBBBBCCCCCCCCCCCBBBBBBBBBBBBBBCCBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCDDDCDCCCCBBAAAAAAAABBCCDDDDDDDDDDDDDDDDDDDDDDDDDCCBBAAAAAABBCCCDDDDDDDDDDDDDDDCCCDDCCCCCCDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCBBBBBCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCDDCCDDCCDCCCBBBAAAAAAABBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDCBBAAAAABBBCCCDDDDDDDDDDDDDDDDDDDDDCDDDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCDDCCCCBBBBBAAAAABBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCBBAABBBBBCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDCCDCCCCBBBBBAAAAABBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCBBBBBBBBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCBBBBBBAAABBBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBBBBBBBCCCDDDDDDDDDDDDDDDDDDEDDDDDDDEDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBBBBBCCCCCDDDDDDDDDDDEEDDDDEEEEEEEEEDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCBBBCCCCCCCDDDDDDDEDDEEEEDDDEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDCCDCCCBBBBCBBBBBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCBCCCCCCCDDDDDDEDDDDEDDDEEEEEEEDEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDCCCCCBCCCBBBBBCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCDDDDDEDDDDDEDDDEEDDEDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDCCCCBCCCCBBBCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCDDDDDDDDDDEDEDDEEDEDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCDDCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCDCCDDDDDDDDDDDDDDEEDDEEEDDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCDDDDDDDDDDDDDDDDDEEDDDDEEDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEDEEDDDDEEDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEDEEDDDDEEDDDDD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEDEEDDDEEEEEEEE
}

