# FE 专用 StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: doris-fe-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# BE 专用 StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: doris-be-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer