apiVersion: v1
kind: PersistentVolume
metadata:
  name: fe-local-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: doris-fe-storage
  local:
    path: /var/bigdata/servers/doris/data/fe
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube